security:
  firewalls:

    login:
      pattern: ^/api/login
      stateless: true
      anonymous: true
      form_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    api:
      pattern: ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  providers:
    in_memory:
      memory:
        users:
          user:
            password: password
            roles: 'ROLE_USER'